services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: spring-xml
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  spring-boot-xml:
    build: ./
    container_name: spring-boot-xml
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123456
      POSTGRES_DB: spring-xml
    ports:
      - '8080:8080'